### ISSUE TITLE
Unable to 'run' source code file

### ISSUE THREAD

**Issue by holgerbrandl** [holgerbrandl/r4intellij#10]
_From [S.N.Maij...@gmail.com](https://code.google.com/u/106522926405148909180/) on February 18, 2012 00:11:42_

[What steps will reproduce the problem?]
Conversely, no steps can avoid this problem.

[What is the expected output? What do you see instead?]
I expect an R interpreter to be configurable and run a R script file. This should be very easy to implement if the R executable is in the PATH. Without this, and with the lack of sourcing R code in an R session on my platform, the plugin can hardly be considered for the more advanced features that are there now.

[What version of the product are you using? On what operating system?]
- Intellij IDEA 11.0.2
- R4Intellij 0.6
- modern Linux

[Please provide any additional information below.]

_Original issue: http://code.google.com/p/r4intellij/issues/detail?id=30_

**Comment by holgerbrandl** [comment]
At the moment the only way is to define R as an external tool and run it over the script:

1) Define the external tool
![image](https://cloud.githubusercontent.com/assets/200952/21801060/6114f6b8-d720-11e6-863f-ea51099e39aa.png)

2) run it over the script: Tools->External Tools->

**Comment by holgerbrandl** [comment]
solved for 1.0

**Comment by iOSHK** [comment]
Hello,
I am trying to run R in Intellij IDEA, but can't get it to run.
I am running windows 10. I already have the R4Intellij plugin installed.
I am currently trying to setup the external tool as you have explained, but I keep getting the error message
_Fatal error: you must specify '--save', '--no-save' or '--vanilla'
attached is a screen shot of the  error message and external edit tool configuration

![image](https://cloud.githubusercontent.com/assets/26525367/24082685/9540f6d4-0d04-11e7-8656-2d6a01c76d44.png)


![image](https://cloud.githubusercontent.com/assets/26525367/24082648/27856968-0d04-11e7-9d2e-7adb34c7bea6.png)

what am I getting wrong?
Thanks

**Comment by holgerbrandl** [comment]
the parameters would need to be:
```
 -f "require(Rserve); Rserve(args=...)"
```

However stay tuned for the upcoming version which will have proper run configurations.

**Comment by iOSHK** [comment]
I still have an issue here. Am getting the '-f' requires an argument error.

![image](https://cloud.githubusercontent.com/assets/26525367/24211723/ea68607e-0f67-11e7-81ee-468cd24d5b20.png)

**Comment by holgerbrandl** [comment]
Indeed `-f` is for files and you would need `-e` for expressions.

**Comment by iOSHK** [comment]
Great, thanks a lot. Finally connected to R, but I can't get any output. Process just exits with code 0

![image](https://cloud.githubusercontent.com/assets/26525367/24313772/51e6c0e4-1119-11e7-8f53-e54203b26222.png)

**Comment by holgerbrandl** [comment]
What did you expect to happen? Running Rserve won't give any output by itself.

**Comment by iOSHK** [comment]
My bad. I thought that Rserve was to help connect R to other environments and then run R scripts. So how do I get to run my R scripts and output within intellij IDEA?

**Comment by holgerbrandl** [comment]
Regular run configurations were added with v1.0
![image](https://cloud.githubusercontent.com/assets/200952/25168343/74a039fc-24e3-11e7-923b-451dc7a15b28.png)
