### ISSUE TITLE
No packages recognized

### ISSUE THREAD

**Issue by kenahoo** [holgerbrandl/r4intellij#102]
<img width="214" alt="screen shot 2017-05-30 at 4 16 47 pm" src="https://cloud.githubusercontent.com/assets/111939/26605423/884ed130-4553-11e7-88e7-b5ac2b8620fe.png">

None of the site-installed packages I'm using are recognized as present, see screenshot.  If I fire up the R console (even inside IDEA) I can successfully load the packages, but the plugin doesn't see them.

**Comment by holgerbrandl** [comment]
Could you check if the plugin was able to build an index under "external libraries" in the project tool window: Something like
![image](https://cloud.githubusercontent.com/assets/200952/26619498/067f62f0-45df-11e7-92c2-7d1eea45ce03.png)

If not could you make sure that the R interpreter is correctly set
![image](https://cloud.githubusercontent.com/assets/200952/26619528/1a0d6498-45df-11e7-89b1-c24adf1ea817.png)

Are there any error messages?

**Comment by holgerbrandl** [comment]
Closed due to inactivity.

**Comment by johnbcoughlin** [comment]
OS X 10.12.6, R version 3.4.1, and Intellij CE 2017.2.3. Version 1.0.8 of the plugin.

I have the same issue, for example with ggplot2. The interpreter path is correct. There is a file `ggplot2.R` in `R Skeletons/r_skeletons`, but it has what looks like a syntax error highlighted:

![screen shot 2017-09-12 at 11 26 56 am](https://user-images.githubusercontent.com/2209490/30342079-4d7fd8ae-97ad-11e7-8612-dbb27b759339.png)

This results in a package resolution error for ggplot2:

![screen shot 2017-09-12 at 11 27 29 am](https://user-images.githubusercontent.com/2209490/30342108-655cdfd0-97ad-11e7-98a7-8ee4dc7e5c9e.png)

There are no error messages that I can see, either in the Event Log or when I rerun `Refresh R Package Index`.
