### ISSUE TITLE
Graphics Window Not Displaying

### ISSUE THREAD

**Issue by kimardenmiller** [holgerbrandl/r4intellij#103]
No results in the Graphics window [using the sample code at the bottom of this page](http://ktisha.github.io/TheRPlugin/).
![image](https://cloud.githubusercontent.com/assets/2165336/26609283/35ef47ba-4555-11e7-9f0c-fe469027853f.png)

Same code works fine using Quartz from the R console.
![image](https://cloud.githubusercontent.com/assets/2165336/26609260/2101d750-4555-11e7-8451-c682c18cf274.png)

PyCharm Community Edition 2017.1.3
Build #PC-171.4424.42, built on May 10, 2017
JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

R Plugin 1.0.5

**Comment by holgerbrandl** [comment]
Indeed the graphics window integration is not functional at the moment. The existing implementation was not ready yet, so we removed it for now. Sorry for inconvenience.
