### ISSUE TITLE
r4intellij for Pycharm?

### ISSUE THREAD

**Issue by evyve** [holgerbrandl/r4intellij#112]
Hello,

I've been trying to install _R Language Support_ in Pycharm Community Edition (the JetBrains website seems to suggest it's compatible). I've got Pycharm Community Edition 2017.1.4 (Linux).

- If I try to install the plugin (from a local file) r4intellij 1.0.5 (zip archive downloaded off GitHub), I get this error: "fail to load plugin descriptor from file r4intellij-1.0.5.zip".

- If I try to install the plugin (from a local file) r4intellij 1.0, the installation appears to be successful, but when Pycharm opens and opens a project, it stalls. It doesn't load the content of any file then issues this error:
![jetbrains r4intellij](https://user-images.githubusercontent.com/28043239/28076141-9d983068-6655-11e7-8512-991bea331b65.png)

Did I misunderstand the compatibility of r4intellij with Pycharm? If not, what can I do to get the plugin working?

With thanks,
Emilie

**Comment by holgerbrandl** [comment]
You should always install it via the intellij/pycharm plugin repository. The zip-file provided on github is just an archive of the source files and not an assembled version of the plugin.
![image](https://user-images.githubusercontent.com/200952/28265927-8660783c-6af2-11e7-8072-04403307dec5.png)

**Comment by holgerbrandl** [comment]
And to actually answer your question: Yes, the r-plugin should be fully compatible with pycharm.

**Comment by evyve** [comment]
Hi,
Thanks for getting back to me. That's how I install the plugin: _Settings_ > _Plugins_ > _Install plugin from disk..._
The plugin is there, but when it's installed, I get the error reported above. Is there some incompatibility between that version of the plugin and that version of PyCharm?

**Comment by holgerbrandl** [comment]
The github archive files are not builds but just source file bundles. You should install it via plugins->"browse repositories"->
![image](https://user-images.githubusercontent.com/200952/28525467-a32177f4-7084-11e7-84dc-87ac78ce55f3.png)

I've just check with pycharm and it works like charm.
