### ISSUE TITLE
how to build R ? Please help me! 

### ISSUE THREAD

**Issue by gem874** [holgerbrandl/r4intellij#126]
I saw this "http://holgerbrandl.github.io/r4intellij/"
How to build R? I don't understand. Please help me!! 

**Step ....** 

1. I install "R Language support" plugin. 
2. And then, File > Setting > Languages & Frameworks > R Language 
* R Interpreter : C:\Program Files\R\R-3.3.3\bin\x64\Rscript.exe (my Rscript.exe interpreter) 
3. Run > Edit configuration > R select 
* Script : test.R 
* Working directory : test.R project position 

4. test code 
print("a")

5. Run result 
"C:\Program Files\R\R-3.3.3\bin\x64\Rscript.exe" --no-save --quiet
file name is missing
Process finished with exit code 1

ps. I already set system variable in my path.  so when I open cmd and insert "R", it works. 
* Path variable add " ;C:\Program Files\R\R-3.3.3\bin\x64 "

I already R-studio, but I want to change my IDE (intellj)

**Comment by holgerbrandl** [comment]
You need to point it to R.exe instead. The IDE will offer a run action for files ending with .R:
![image](https://user-images.githubusercontent.com/200952/30578598-0d9f36f4-9d15-11e7-9021-e2e8b8982f5a.png)

**Comment by gem874** [comment]
Thank u for answer! 
But it is not work :<

"C:\Program Files\R\R-3.3.3\bin\x64\Rscript.exe" --no-save --quiet
file name is missing
Process finished with exit code 1

**Comment by holgerbrandl** [comment]
Because you set Rscript to be the interpreter in the preferences. But it should be R.exe instead.

**Comment by gem874** [comment]
Oh! Thank u very much! 
---> I change R interpreter R.exe! 

And then, File > Setting > Languages & Frameworks > R Language
R Interpreter : C:\Program Files\R\R-3.3.3\bin\x64\R.exe (my Rscript.exe interpreter)
