### ISSUE TITLE
Pushing code to console issue

### ISSUE THREAD

**Issue by nikunj2512** [holgerbrandl/r4intellij#140]
Hi,
In the documentation, it is written that `To push code from the editor to the console use Ctrl+Meta+Enter` but windows 10 don't have Meta key and I have tried all combinations like Ctrl + Enter/ Ctrl + +Shift + Enter/ Ctrl + Shift + Alt + Enter and none of them were able to push the code to the console. Please help.

**Comment by holgerbrandl** [comment]
This functionality has been refactored out into a separate plugin called "send to terminal"
