### ISSUE TITLE
Control-Meta-Enter is not working 

### ISSUE THREAD

**Issue by javadba** [holgerbrandl/r4intellij#144]
I have tried a number of combinations and none of the pushes the code from the editor panel to run in the console (which works just great in the python plugin but with different shortcut).

I am on macos high sierra on 2017.1.5 with the latest R plugin.

**Comment by holgerbrandl** [comment]
This functionality was refactored out into a separate plugin called "Send to Terminal"

**Comment by javadba** [comment]
As mentioned in the Documentation bug : this error is about not pushing code from the editor panel to the R console (not bash). I have tried numerous times and it does not work.

**Comment by holgerbrandl** [comment]
When using `cmd+shift+a` to browse all actions, search for `evaluate` which should list it along with the current key binding:
![image](https://user-images.githubusercontent.com/200952/36355929-1db2ca26-14eb-11e8-9fae-99556172c23f.png)

**Comment by javadba** [comment]
This is interesting: running it *that* way  ie from the `Search Actions`
DOES work.  But invoking ctl-shitf-enter does .. *nothing* .

2018-02-18 11:34 GMT-08:00 Holger Brandl <notifications@github.com>:

**Comment by holgerbrandl** [comment]
Did you make sure that the focus is in the R editor in a line that contains code (or that some code is selected)? For debugging purpose you may want to try it also in a document without syntax errors.

**Comment by javadba** [comment]
This is actually not the problem: it is that the console is not scrolling - so I did not realize anything were happening.  (I opened a separate bug).
