### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by javadba** [holgerbrandl/r4intellij#145]
A bug was just closed in which a feature highlighted prominently on the README - and which does not work out of the box - has been moved to a plugin. That's fine - but how does a (very interested) user discover this - and other goodies/gotchas within this plugin? 

Re: https://github.com/holgerbrandl/r4intellij/issues/144

but not documented on this page: http://holgerbrandl.github.io/r4intellij/ that instead shows:

<img width="941" alt="screen shot 2018-02-07 at 6 56 58 am" src="https://user-images.githubusercontent.com/410769/35923181-5ab801f4-0bd4-11e8-88d9-293010d71fab.png">

**Comment by holgerbrandl** [comment]
Actually, I was thinking to you intended to send the code to  bash terminal (for which you need the additional plugin). For the embedded console ctrl-meta-enter should work (and does for me). You could check the shortcut assignment in ther keymap prefernces under
![image](https://user-images.githubusercontent.com/200952/35982407-04fecb54-0cf0-11e8-901a-b2db9d4daec6.png)

So imho the docs are fine. Even the additional plugin is documented below the referenced screenshot.

**Comment by javadba** [comment]
it does not work for me : so then .. back to re-opening the other bug..
