### ISSUE TITLE
R language support

### ISSUE THREAD

**Issue by rajeevbkn** [holgerbrandl/r4intellij#147]
"No R interpreter defined: Many R related features like completion, code checking and help won't be available. You can set an interpreter under Preferences->Languages->R".
The above message is flashed when Pycharm is opened after installation. When a plugin is downloaded from Holger's website and then the folder is directed in Preferences -> Languages -> R then the IDE flashes a message that permission to folder is denied.

**Comment by holgerbrandl** [comment]
Hey, why would you download something directly (and what actually and from what website)? The recommended way to install the plugin is via the plugin manager in intellij.

**Comment by a211212abc** [comment]
Hi @holgerbrandl ,

I'm also encountering this problem with . And I also tried several times to reinstall R language support plugin in intellij's plugin manager page. But it still cannot infer the right path of the interpreter. Could you please show that how to configure the path manually? 

Lots of thanks

**Comment by holgerbrandl** [comment]
Closed due to inactivity. Feel welcome to reopen the ticket if the problem remains.

**Comment by vherasme** [comment]
Hi. I have seen this error when opening pycharm:

```
java.lang.RuntimeException: failed to split package-version in line 'Fatal error: R home directory is not defined'.
 Helper output was:
Fatal error: R home directory is not defined

```
Is it the same issue or should I open another ? By the Way I need to know how to set the R folder in linux. This might be the cause

**Comment by holgerbrandl** [comment]
I think it's a separate issue. Could you attach the complete stacktrace to a new ticket?
