### ISSUE TITLE
linting not working with built-in functions correctly

### ISSUE THREAD

**Issue by dvincentwest** [holgerbrandl/r4intellij#151]
System:
- Windows10 64-bit
- PyCharm 2017.3.4 64-bit
- R 3.4.3 64-bit

I am very new to R, but very familiar with Python.  First off thanks very much for the plugin

I am having some trouble with the initial configuration and don't know if this is a user error or a bug.

R has indexed my installed packages correctly.  I know this because it gave linting warnings initially, then I installed the packages and the linting warnings went away.

However I am getting unresolved reference warnings on built in functions like `length, all, source, vector` etc.

See the picture below where the function `evalSource` is recognized, and an autocomplete box pops up with suggestions for `eval`, but the function `source` is underlined with an unresolved reference error.  Am I missing something here?

![image](https://user-images.githubusercontent.com/9872343/37526175-ae62e3ba-28fc-11e8-81d7-e126a1767f9c.png)

**Comment by holgerbrandl** [comment]
Could you check if the base package was indexed correctly? To do so, check if under `External Libraries -> R -> r_skeletons -> base.R` is present.
![image](https://user-images.githubusercontent.com/200952/37565397-061c6754-2aa9-11e8-8b21-48d3365b746d.png)

**Comment by dvincentwest** [comment]
it is not there.  Can I trigger a build of it somehow?

![image](https://user-images.githubusercontent.com/9872343/37566430-12c05f64-2a87-11e8-942d-d722e833db4c.png)

**Comment by holgerbrandl** [comment]
I don't think so since it managed to skeletonize most of the other packages in your installation.

Could you build the skeleton for `base` manually as described under http://holgerbrandl.github.io/r4intellij/faq.html#r4intellij-fails-to-index-package-xy-what-canshould-i-do and attach the results in here?

**Comment by dvincentwest** [comment]
It runs for a couple of minutes but then nothing changes, and the .base.failed icon reappears.  There are no messages output in the Event Log

![image](https://user-images.githubusercontent.com/9872343/37570751-aa9d2b7a-2ac1-11e8-987e-ce9969bcdd95.png)

**Comment by holgerbrandl** [comment]
Follow the link! The idea there is to run the corresponding bits outside of idea and to capture all output incl errors.

**Comment by dvincentwest** [comment]
Right!  Never let anyone tell you I'm great at following directions.  
base.skeleton.R (renamed to .txt to be compatible with github) is attached here.  17000+ lines!  I owe you a very big thank you

[base.skeleton.txt](https://github.com/holgerbrandl/r4intellij/files/1823373/base.skeleton.txt)

**Comment by dvincentwest** [comment]
Scanning over the skeleton file, based on a quick perusal and the `## EOF` at the end of the file it appears that the output completed without errors.

I renamed it to base.R and placed the file in the folder:
C:\Users\\%USERPROFILE%\PyCharmCE2017.3\system\r_skeletons\1343015225

Just to see what would happen.  It seems it now recognizes the functions and objects from base, but doesn't think they are yet imported.  Obviously they weren't meant to be used this way but I thought it was worth a shot!

![capture](https://user-images.githubusercontent.com/9872343/37574537-91e48b2c-2aef-11e8-9eac-767e5b875cf9.PNG)

**Comment by dvincentwest** [comment]
Okay, so... ... what to say.  Since I last posted:

0. Updated to the latest R plugin version (that was actually earlier today before my last post)
1. Spent some time playing around with emacs
2. Installed the `lintr` package in R
3. Opened a completely new project (within PyCharm) to work on some R files.  My fan started spinning like crazy and skeletons started rebuilding and now everything works

I don't know if any of the above three (not 1 obviously) things had anything to do with what changed... at this point, everything is working, evaluation in the console is working... its working.  I don't know why I was having problems before or why its all of a sudden working now.  If something is obvious I'd love to know what happened.  Otherwise, I suppose we can close this one out

![capture](https://user-images.githubusercontent.com/9872343/37576522-e1b9a73a-2afa-11e8-917e-f541cacdf210.PNG)

**Comment by holgerbrandl** [comment]
Sure, please come back in case the plugin fails to be fun. Just be patient, It's just a hobby project, so some issues might take a while to solved.
