### ISSUE TITLE
R plugin not working

### ISSUE THREAD

**Issue by J-o-n-a-t-h-a-n** [holgerbrandl/r4intellij#156]
Hi,

I've installed the R Language Support on PyCharm, but I receive weird German errors:

Warnung: Namensraum ‘ggplot2’ ist nicht verfügar und ist durch.GlobalEnv ersetzt worden während Objekt ‘consumption_boxplot’ verarbeitet wurde

Process finished with exit code 0

Effectively, I cannot process any R code, not even something simple like print('Hi')

Any ideas? Thanks!

**Comment by holgerbrandl** [comment]
Could you post a screenshot of the error?
It seems more related to your R installation to me.

**Comment by holgerbrandl** [comment]
Closed due to inactivity. Feel welcome to reopen the ticket if the problem remains.
