### ISSUE TITLE
F1 for R-Help integration not working

### ISSUE THREAD

**Issue by latinostats** [holgerbrandl/r4intellij#158]
Hello @holgerbrandl 
great work with the plugin!
The F1 key for the R-help support is not working for me. Is there a configuration I need to check? F1 is triggering the IntelliJ Help instead.
any help will be appreciated

Mario

**Comment by holgerbrandl** [comment]
F1 will just work if the cursor is on an R function name.

**Comment by latinostats** [comment]
@holgerbrandl ... still does not work... I put the cursor on
rnorm()
library(dplyr)
win.version()
ans still getting the Intellij help in the browser

**Comment by holgerbrandl** [comment]
Can you start an R terminal in Intellij?

**Comment by holgerbrandl** [comment]
I think this and the other ticke submitted by you are the same internal problem, which is that it fails to start the internal help-server. So I'd suggest to close this ticket and focus on the #159.
