### ISSUE TITLE
No graphics in the "R Graphics" window

### ISSUE THREAD

**Issue by sunqingyao** [holgerbrandl/r4intellij#160]
I was running the following code:

```
library(ggplot2)

gg = ggplot(mpg, aes(displ, hwy, colour = class)) +
    geom_point()
(gg)
```

I got nothing besides a line saying `Process finished with exit code 0`.

![screen shot 2018-05-09 at 20 13 34](https://user-images.githubusercontent.com/13443062/39814081-83e43834-53c5-11e8-9d16-6e21a145b2f3.png)

How can I view the beautiful graphics in the top-right "R Graphics" window? Thank you!

**Comment by holgerbrandl** [comment]
It's disabled (see duplicate #134) since we don't really  know how to do so. The correct way would be to implement a custom graphics device, but thats a tricky one. PRs are welcome!
