### ISSUE TITLE
How to index source files

### ISSUE THREAD

**Issue by JonathanQiangLi** [holgerbrandl/r4intellij#175]
I know this may be an enhancement request:

In my R project, I have developed my own functions and placed them in a R file. Is there a way for the plugin to index those functions as well? 

Thanks!

**Comment by holgerbrandl** [comment]
It's already possible. Just check "Resolve variables in all module files" in the preference panel. This works for me:
![image](https://user-images.githubusercontent.com/200952/45114629-c6c1fc00-b14d-11e8-8f10-465ea5690312.png)
What's somehow not yet there is completion for those items. But this would a separate ticket imho.
