### ISSUE TITLE
Remote Interpreter

### ISSUE THREAD

**Issue by rrazaghi** [holgerbrandl/r4intellij#179]
Hi and thanks for the great tool. is there a way to have an option to set up a remote R interpreter through SSH for example?
I am using this in pycharm.
Thank you,
Roham

**Comment by holgerbrandl** [comment]
What I do is to simply in my daily setup is to use https://github.com/holgerbrandl/send2terminal to push code from idea into a remotely running R via some shell-terninal.

Feel welcome to reopen if needed.

**Comment by rrazaghi** [comment]
awesome, thanks. then the R Graphics tab cannot be used this way, right?

**Comment by holgerbrandl** [comment]
No but it's non-functional anyway at the moment. I typically simply use a forwarded x-device
