### ISSUE TITLE
Dual exceptions for 'IRkernel' and 'pbdzmq'

### ISSUE THREAD

**Issue by shivendra90** [holgerbrandl/r4intellij#182]
Was writing a sample R script when pyCharm threw these exceptions:
     java.lang.Throwable: Failed to generate skeleton for 'IRkernel'. The error was:

    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: 
    /Library/Developer/CommandLineTools/usr/bin/xcrun
    Error: package or namespace load failed for ‘IRkernel’:
    .onLoad failed in loadNamespace() for 'pbdZMQ', details:
     call: if (id[2] != fn.dylib) {
     error: missing value where TRUE/FALSE needed
    In addition: Warning message:
    In system(paste(cmd.ot, " -D ", fn.dylib, sep = ""), intern = TRUE) :
    running command '/usr/bin/otool -D /Users/Shiv/Library/R/3.5/library/pbdZMQ/libs/libzmq.5.dylib' 
    had status 1
    Execution halted

    If you think this issue with plugin and not your R installation, please file a ticket under 
    https://github.com/holgerbrandl/r4intellij/issues

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:236)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Similar exceptions for modules 'pbdZMQ' as well as 'tcltk' that I'm including in the below txt file instead of pasting the whole message.

[error.txt](https://github.com/holgerbrandl/r4intellij/files/2519206/error.txt)

**Comment by holgerbrandl** [comment]
Thanks for reporting the issue.

**Comment by ktisha** [comment]
Looks like the problem appears after the OS update and caused by the license agreement in Xcode.

Open the Terminal App and enter:
```
xcode-select --install
```
See more information here -- https://apple.stackexchange.com/questions/254380/macos-mojave-invalid-active-developer-path
