### ISSUE TITLE
foo R Script in menu New .. file list

### ISSUE THREAD

**Issue by piotrv** [holgerbrandl/r4intellij#208]
OS: Arch Linux, tcl8.6, tk8.6
IDE: PyCharm 2019.2.3
Plugin: R Language Support 1.1
R Language | R Intepreter: /usr/bin/R
Invalidate Caches/ Restart

When creating a new R script with `New` .. , the R Script File 'template' in menu file list shows up as **_foo_** and not as _R Script File_
![Screenshot_2019-10-05_21-32-10](https://user-images.githubusercontent.com/3855916/66265945-b1bb0f00-e81e-11e9-8167-581a620b90a9.png)
(see screenshot)

**Comment by holgerbrandl** [comment]
Already fixed in master
