### ISSUE TITLE
PyCharm CE - NoClassDefFoundError: com/intellij/openapi/actionSystem/DataKeys

### ISSUE THREAD

**Issue by holgerbrandl** [holgerbrandl/r4intellij#26]
_From [RonaldoC...@gmail.com](https://code.google.com/u/111658536644905715915/) on April 23, 2014 10:55:17_

What steps will reproduce the problem? 1. Install PyCharm CE (Community Edition) , R and r4intellij
2. Crate a new .R file
3. Right click a command and then R Code Evaluation - Evaluate What is the expected output? What do you see instead? Code should be evaluated in R session What version of the product are you using? On what operating system? r4intellij 0.8.2 - Mac OS Montain Lion Please provide any additional information below. I get the following on the event log:

NoClassDefFoundError: com/intellij/openapi/actionSystem/DataKeys: com/intellij/openapi/actionSystem/DataKeys

_Original issue: http://code.google.com/p/r4intellij/issues/detail?id=48_

**Comment by holgerbrandl** [comment]
can't reproduce

**Comment by sanderd** [comment]
Duplicate issue @ https://github.com/holgerbrandl/r4intellij/issues/43
Facing same problem in Webstorm 10.
