### ISSUE TITLE
NoSuchMethodError: Error during dispatching of java.awt.event.InvocationEvent[INVOCATION_DEFAULT

### ISSUE THREAD

**Issue by ravichips** [holgerbrandl/r4intellij#37]
OS: Mac OS X
Idea Version: 12.1.7
JRE: 1.6.0_65

Issue: File not displayed in editor.  Error Msg while reading a .R file:
11:08:21 PM NoSuchMethodError: Error during dispatching of java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.intellij.ui.mac.MacFileChooserDialogImpl$2$2@6edd475a,notifier=null,catchExceptions=false,when=1421467700550] on apple.awt.CToolkit@1779e93: com.r4intellij.lang.parser.GrammarParserUtil.current_position_(Lcom/intellij/lang/PsiBuilder;)I

**Comment by holgerbrandl** [comment]
Hi ravichips,

would it be possible to attach the file to the ticket? In general we just test and support recent versions of intellij (which is v14v at the moment). So maybe we should prevent the installation on older Intellij versions.

**Comment by ravichips** [comment]
Hi Holger,
It works on Idea 14C.When you say "attach the file" do you mean the .R file?
Thanks for your quick response.
Ravi

**Comment by holgerbrandl** [comment]
You can attach files in to the github ticket. Just drag them into the comment area. It will just work on the website, not per email i think.
