### ISSUE TITLE
Beginner help - how to send current line to R

### ISSUE THREAD

**Issue by mattdowle** [holgerbrandl/r4intellij#48]
Sorry for the dumb question. I'm a new IntelliJ user and your plugin looks awesome.  I've installed it ok and opened a .R file and the syntax colouring seems to work fine.   But what do I press to send the current line to the R session running in the Terminal.   I can obviously start a Terminal inside IntelliJ and start R in it by typing R at bash prompt,  but I don't see an R menu added to the IntelliJ menu or how you get to the screenshot on this project's README.md under "Integration with R session" section.
Armed with the answer I'm happy to submit pull request to README.md.
Thanks in advance.

**Comment by mattdowle** [comment]
Ok so right click!  Now I get the menu you show in README.md and "R Code Evaluation" and the "Evaluate" item.   I selected a line of R and clicked "Evaluate" but nothing appears to happen.  I started R in the Terminal and tried again but nothing happened.   Btw, I just want to send the current selection to the Terminal, whatever the Terminal might be running at the time (usually either bash or R).

**Comment by holgerbrandl** [comment]
HI Mattdowie,

r4intellij does not work with the builtin terminal of Intellij yet. On Macos in can send the current line or selection to the terminal, iterm2, or to R.app. Under Windows it should send it to the R application. It's not yet supported under linux, because there's not generic way to communicate between apps on linux.

The shortcuts to do it are visible right next the action items in the context menu.

I hope this answers your question.

**Comment by mattdowle** [comment]
Ok but I am on Macos.

> On Macos in can send the current line or selection to the terminal, iterm2, or to R.app.

Great.  But exactly how.  I have clicked R Code Evaluate ->  Evaluate  and nothing happens.

**Comment by mattdowle** [comment]
Ah. Now I see that a new R app was started. That wasn't clear to me! It just appears in the dock and didn't come to the front of the screen. Ok so now I see that Ctrl+Option+Enter does send the line to R.

Still stuck on how to send the current line to the terminal/iterm2.   How to do that please?

**Comment by holgerbrandl** [comment]
You can change the evaluation target in the preferences.

There you can also change the focus behaviour. The default is here that the focus stays in intellij, but you can also change it so that it changes to the evaluation target.

**Comment by mattdowle** [comment]
Ok got it now. I changed evaluation target in preferences to Terminal and also changed Evaluate shortcut to a single F5 keypress.  This is exactly what I wanted.  Plus, evaluate sends to the last active Terminal,  which is exactly what I wanted too so I can have multiple Terminals (similar to NppToR on Windows). This is awesome!    Never found a way to do this on Linux/Ubuntu,  so very happy.
I'll submit a pull request to README.md ...

**Comment by holgerbrandl** [comment]
Actually it does not work on linux/ubuntu but just on macos. :-( All it's doing is to use applescript to remote-control the terminal/iterm/r.app. I'd love to add it for linux as well, but there does not seem any java-accessible framework to do it.

**Comment by mattdowle** [comment]
I never found a way in linux either and would like that as well.  This ability, rightly or wrongly, is the main reason I'm sticking with Mac for now.
