### ISSUE TITLE
R code evaluation disabled in intellij14 Windows

### ISSUE THREAD

**Issue by ghost** [holgerbrandl/r4intellij#50]
Hi 

I am not able to run the R code since the option is disabled. Any help is appreciated.

**Comment by holgerbrandl** [comment]
what's your operating system and version of idea?

**Comment by vinodhkrishnaraju** [comment]
Hi

Windows 8.1 and 14.1 intellij

Best regards
Vinodh

**Comment by holgerbrandl** [comment]
do you get syntax highlighting and code error warnings in the editor? What's selected as evaluation target in the R4intellij preferences?

**Comment by vinodhkrishnaraju** [comment]
Hi

I don't get syntax highlighting and warnings.

Regards
Vinodh
LinkedIn <https://www.linkedin.com/pub/vinodh-krishnaraju/12/245/43>

**Comment by holgerbrandl** [comment]
are there any exception warnings in the intellij console?

**Comment by Andorxor** [comment]
Hi, that is also a problem in my case. I do not know what you mean by intellij console, I did not find nothing suspicious at least.  This is the only thing in idea log that I could relate to R4intellij:
>RPackageCache - loading r-package cache 
>RPackageCache - loading of r-package cache done 

any ideas?

**Comment by holgerbrandl** [comment]
Are you using intellij14 as well?

**Comment by Andorxor** [comment]
Yes, it is 14.1.2 Ultimate under Win 7.

**Comment by sanderd** [comment]
Long-shot, but are your files named *.R? 
Mine were a lowercase *.r and was facing the same grayed-out menu item.

**Comment by Andorxor** [comment]
The file is named as *.r, changing it to *.R didn't solve the issue, however.

**Comment by holgerbrandl** [comment]
Closing because was not reported again.
