### ISSUE TITLE
"else if" instruction is marked as incorrect

### ISSUE THREAD

**Issue by eschava** [holgerbrandl/r4intellij#51]
Intellij IDEA 14.1.3
R4Intellij 0.9.1

Screenshot attached

https://dl.dropboxusercontent.com/u/450959/screenshots/screen150521-124426.png

**Comment by holgerbrandl** [comment]
This bug has been fixed already  but has not been deployed as a new version. The new version will come as soon as the new reformatter is a bit more stable. Sorry for inconvenience in the meantime.
