### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by nite** [holgerbrandl/r4intellij#57]
Is it possible to implement [pretty R syntax highlighting](http://www.inside-r.org/pretty-r) in r4intellij?

**Comment by holgerbrandl** [comment]
we already have customizable highlighting. I like the idea of linking out inside-r.org. The html-copy is part of intellij and we get it for free (I think). Do I miss something which your link can do?

In addition the long awaited reformatter is just being tested and will be part of the next release

**Comment by holgerbrandl** [comment]
closing because does not seem relevant anymore
