### ISSUE TITLE
Code completion for brackets and parentheses.

### ISSUE THREAD

**Issue by TariqAHassan** [holgerbrandl/r4intellij#63]
Two quick things regarding brackets and parentheses.

**1**. Autocomplete, e.g., ' {**|** ' being automatically replaced with ' {**|**} ', where **|** is the curser.
IntelliJ's 'insert pair }' does not completely solve this problem.

**2**. Indent on enter if between curly brackets, 
e.g. if(T = T){**|**} 

--Enter to yield-->

if(T = T){
........**|**
} 

Is it possible to implement either of these?

**Comment by holgerbrandl** [comment]
1. this seems the default behavior in intellij if "Insert pair bracket is enabled"

2. This will be partially possible by using the r-code-reformatter which is in the works.

**Comment by holgerbrandl** [comment]
1. bracket completion works in v1.0; 
2. indent on enter works in v1.0

Feel welcome if you've further questions
