### ISSUE TITLE
Does not correctly parses line breaks

### ISSUE THREAD

**Issue by uladz** [holgerbrandl/r4intellij#67]
Consider this:

```
if (zzz == 1) {
  # do something
}
else if (zzz == 2) { # R4IntelliJ reports syntax error here, wrong
  # do something else
}
else { # R4IntelliJ reports syntax error here too, wrong again
  # do something else again
}
```

R4IntelliJ reports syntax errors incorrectly here.
The same happens at this case too:

```
f <- function( # R4IntelliJ reports syntax error here, wrong
  x)
{
}
```

All valid syntax, just different coding style.

**Comment by holgerbrandl** [comment]
The if else example is invalid R code. Just paste it into an R-console. The reason is that the intial if block is a valid expression by itself can/will be evaluated on its own. The downstread else has no matching if that's why you see the error.

the second example with the function definition works for me. Could you create a scratch-R files with just the following content:
```
1+1


f <- function( # R4IntelliJ reports syntax error here, wrong
x)
{
}
```
and let me know if this works without parser error. (It does for me).

**Comment by uladz** [comment]
Actually all my R code is written in this style so if-else is a _valid_ R syntax. The is a difference how R processes source files and interactive typed code as I recall. This style works when you source an R file but will error out if you copy-paste in R console.

2nd still example errors out:
<img width="674" alt="screen shot 2016-05-18 at 10 09 10 am" src="https://cloud.githubusercontent.com/assets/1396204/15368035/b580c3e4-1ce0-11e6-98f5-33f561d5611e.png">

**Comment by holgerbrandl** [comment]
The if else is also not parsed correctly in rstudio so I think r4intellij is working correctly
![image](https://cloud.githubusercontent.com/assets/200952/15375333/c34076a0-1d4e-11e6-8150-be7c2b39b08e.png)
This also seems consistent with https://github.com/antlr/grammars-v4/blob/master/r/R.g4 where `else` must be preceeded by an expression without any newline inbetween.

**Comment by holgerbrandl** [comment]
The function declaration is indeed valid R code. It seems that the parser does not allow for comments at the beginning of function signatures.  A slightly changed version works fine
```
f <- function(x # R4IntelliJ reports syntax error here, wrong
,x)
{
}
```

 I'll have a look asap.

**Comment by uladz** [comment]
StatET correctly parse and does not produce any syntax error for the if-else example. And again, I want to emphasize that we have a 10,000+ enterprise R project that is written in this style. I have tried to switch to R4IntelliJ instead of Eclipse+StatET and had to get back to StatET for now because of this syntax issue. It basically breaks parsing and I do not get no code completion, no parsing, no outline right after 1st if-else statement in my code. And I want to emphasize again that this is R-compliant code for R "batch" mode. Thansk!

**Comment by holgerbrandl** [comment]
Even sourcing does not work for me:
```
[brandl]$ cat test.R 
zzz=1
if (zzz == 1) {
  # do something
}
else if (zzz == 2) { # R4IntelliJ reports syntax error here, wrong
  # do something else
}
else { # R4IntelliJ reports syntax error here too, wrong again
  # do something else again
}
[brandl]$ R -e "source('test.R')"

R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> source('test.R')
Error in source("test.R") : test.R:5:1: unexpected 'else'
4: }
5: else
   ^
Execution halted

```

**Comment by uladz** [comment]
Aaaah, my bad, I mislead you about sourcing vs parsing. It works only if you define this inside of a function. At the top level it throws an error. The difference is how function are evaluated I think. Anyway, here's working example of if-else construct:
```
[vlad@Vlads-MacBook-Pro.local tmp]$ cat test.R 
f <- function(x) {
  if (x == 1) {
    print("do something")
  }
  else if (x == 2) {
    print("do something else")
  }
  else {
    print("do something else again")
  }
}
f(1)
[vlad@Vlads-MacBook-Pro.local tmp]$ R -e "source('test.R')" 

R version 3.3.0 (2016-05-03) -- "Supposedly Educational"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> source('test.R')
[1] "do something"
> 
> 
[vlad@Vlads-MacBook-Pro.local tmp]$ R -f test.R 

R version 3.3.0 (2016-05-03) -- "Supposedly Educational"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> f <- function(x) {
+   if (x == 1) {
+     print("do something")
+   }
+   else if (x == 2) {
+     print("do something else")
+   }
+   else {
+     print("do something else again")
+   }
+ }
> f(1)
[1] "do something"
> 
```

**Comment by holgerbrandl** [comment]
Indeed, this works and is valid code, which the [R lang specs](https://cran.r-project.org/doc/manuals/R-lang.html#if) confirms implicitly:
> When the if statement is not in a block the else, if present, must appear on the same line as the end of statement2. Otherwise the new line at the end of statement2 completes the if and yields a syntactically complete statement that is evaluated. 

So by blocking the if-else, the parser behavior is supposed to change. That's really tough from a parser design point of view and I'm not sure I can fix it. I could change it to optionally allow for a NL before an else, but this would not be correct for none-blocked expressions. 

Furthermore breaking lines after else even in a block is considered bad style according to https://google.github.io/styleguide/Rguide.xml#else

Personally I think that this is actually a flaw in the R language design. Expressions must have a consistent grammar no matter where they are being used.

Thanks to @andreirozanski for the value feedback on this issue. :-)

**Comment by uladz** [comment]
Unless you can identify when the code is in a function scope or in a global environment and switch between two different parsing "flavors" having a config in options would be the best options here I guess. At least it will resolve my issue ;). Thanks!

**Comment by holgerbrandl** [comment]
Won't fix for now, because not enough use-cases. Feel welcome to reopen the ticket needed.
