### ISSUE TITLE
Please add support for running selected R code in console just like R Tools for Visual Studio does.

### ISSUE THREAD

**Issue by cpedia** [holgerbrandl/r4intellij#77]

**Comment by holgerbrandl** [comment]
It does so in the upcoming version:
![image](https://cloud.githubusercontent.com/assets/200952/23609900/9b309340-0270-11e7-9c55-16655c0408a5.png)

I'll keep this ticket open until the version has been released (hopefully later this week).

**Comment by cpedia** [comment]
bravo!

**Comment by holgerbrandl** [comment]
v1.0 has been released. See http://holgerbrandl.github.io/r4intellij/#interactive-console

**Comment by quazi-irfan** [comment]
For anybody stumbling over this thread, for the Ctrl+Meta+Enter key combination does not work on windows, and the user need to update the key bindings.
