### ISSUE TITLE
Failed to generate skeleton for '<some selected R packages>'. Exit code: 1

### ISSUE THREAD

**Issue by pokulo** [holgerbrandl/r4intellij#82]
This [1] is maybe simply due to missing R package dependencies. Had a similar problem with some Python packages in PyCharm as well. The SkeletonGenerator was just unable to generate skeleton code for all packages. It could also be due to write-protection of Ubuntu's r-base-core package's install locations, that do not allow in-place skeleton generation.

Reading the code in "RSkeletonGenerator.java:263", this is simply a LOG-Message, telling that `skeletonize_package.R` exits with error code 1. But I don't know, what let the script fail. I guess it is a configuration problem.

Where to configure other R library locations? In `Settings->Languages & Frameworks->R Language` I can only define the R Interpreter location and tick `resolve variables in all module files`. The subsection `Code Insight` is empty!? OK, this is a Python-Project, because it is PyCharm.... Is there something like an R-Project? Could  not find such.

[1]
```
Failed to generate skeleton for '<some selected R packages>'. Exit code: 1
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:263)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by holgerbrandl** [comment]
One reason could be a missing interpreter. The next patch release will skip index updates if the interpreter is not defined.
Another reason is that the plugin actually failed to index a certain package. I run it against a few hundred common ones and could not spot any issue, but I guess some packages might fail to index. Could you indicate which package in particular failed to index?

> It could also be due to write-protection of Ubuntu's r-base-core package's install locations, that do not allow in-place skeleton generation.
Indices are created in the Intellij Cache directory under which should be always writable. For linux this will be  `~/.<PRODUCT><VERSION>`

> Where to configure other R library locations? I
R library locations are created and maintained internally and are automatically attached to modules, 
![image](https://cloud.githubusercontent.com/assets/200952/25221158/62a66c68-25b4-11e7-8bf8-5d59d715e3e7.png)
![image](https://cloud.githubusercontent.com/assets/200952/25221172/6c21cc06-25b4-11e7-81f1-0ef89b7c9658.png)

> . The subsection "Code Insight` is empty?
There are some settings for code insight already but I have not found time yet to add an UI for them. I've added a placeholder label for now to make this more clear.

**Comment by pokulo** [comment]
I maually tried to run 
```
Rscript /home/poku/.PyCharm2017.1/config/plugins/R4Intellij/skeletonize_package.R tcltk tcltk.skeleton
```
to find out, what is missing. But, as I am not familiar to R, I don't have a clue, what this means:
```
[1] "writing skeleton of  tcltk into tcltk.skeleton"
Error in match(packages, db[, "Package"], nomatch = 0L) : 
  argument "db" is missing, with no default
Calls: unlist -> lapply -> package_dependencies -> match
Execution halted
```

**Comment by pokulo** [comment]
from the log-file, I could extract a list of failing skeleton generations:

`assertthat base BH bit64 bit bitops boot class cluster codetools colorspace compiler datasets data.table DBI dichromat digest dplyr foreign ggplot2 ggvis graphics grDevices grid gtable htmltools httpuv jsonlite KernSmooth labeling lattice lazyeval lubridate magrittr MASS Matrix memoise methods mgcv mime munsell nlme nnet parallel plyr R6 RColorBrewer Rcpp reshape2 rpart rstudioapi scales shiny sourcetools spatial splines stats4 stats stringi stringr survival tcltk tibble tools utils whisker withr xtable`

As I can see, all of them failed due to the `Error in match(packages, db[, "Package"], nomatch = 0L)`.

**Comment by holgerbrandl** [comment]
So it fails for all of them, it seems. 

Maybe the [skeletonizer-script](https://github.com/holgerbrandl/r4intellij/blob/master/r-helpers/skeletonize_package.R) does not work with your version of R. Could you provide me `R -e "sessionInfo()"`? I'm using v3.3.2 without any issues.

**Comment by pokulo** [comment]
```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base    
```

**Comment by holgerbrandl** [comment]
I've traced it down to:
`package_dependencies("devtools", which="Imports")`
which does include the mandatory `db` argument as required by R v3.2. 

In R v3.3 `db` defaults to `NULL` and is thus no longer required..

**Comment by pokulo** [comment]
Thanks! I patched the skeletonizer-script according to bf34168911424126c6b03c172b54b07d966c69ce and get no failing skeleton generation error any more.

**Comment by holgerbrandl** [comment]
The mentioned patch was just good as first glance, but the `NULL` default turned out to be wrong. See yourself:
```
require(tools)
chooseCRANmirror(ind = 1)

package_dependencies("devtools",  db = available.packages(), which="Imports")
package_dependencies("devtools",  db = NULL, which="Imports")
```
The reiterated patch commit was https://github.com/holgerbrandl/r4intellij/commit/b39daac7b6ebe63e175ee16988b734ab6da17ab5

I'd suggest to remove all skeleton-files once the next patch version is installed. Otherwise transitive package dependencies will not be resolved correctly.

**Comment by holgerbrandl** [comment]
Please update to v1.0.3 (by just running ""Check for updates...") which contains a patch for this ticket.
