### ISSUE TITLE
Error in dyn.load

### ISSUE THREAD

**Issue by rwatts3** [holgerbrandl/r4intellij#83]
When I try to run my R file with the latest update, I receive this error in the console.
Any pointers. please note that the `...` are directories that I excluded.

```
Error in dyn.load("/Users/rwatts/Library/Application Support/IntelliJIdea2017.1/R4Intellij/libtherplugin_device64.so") : 
...
Support/IntelliJIdea2017.1/R4Intellij/libtherplugin_device64.so':
...
Support/IntelliJIdea2017.1/R4Intellij/libtherplugin_device64.so, 6): no suitable image found.  Did find:
```

**Comment by holgerbrandl** [comment]
What is your OS? Could you also provide your R version ( `R -e "sessionInfo()"`?

**Comment by rwatts3** [comment]
Mac OS Sierra

results from command.

```
R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.4

locale:
[1] C/en_US.UTF-8/C/C/C/C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.3      packrat_0.4.8-16
```

**Comment by ktisha** [comment]
As far as I understand, It's problem from https://github.com/ktisha/TheRPlugin/issues/33

I've contacted developer and hopefully he can give an update soon.

**Comment by rwatts3** [comment]
awesome thank you I'll standby.

**Comment by holgerbrandl** [comment]
@ktihsa @sproshev I managed to recompile it under macos and the library is loading now under sierra (see f95cfa2). However seeing it in action for the first time, it does not look too convincing to me yet:

1. ggplot fails to render and just gives an almost empty plot. E.g. `require(ggplot2); ggplot(iris, aes(Species)) + geom_bar()` (see screenshot). Is it the same on ubuntu or do you see the correct plot in the graphics device? `base`-plots seem fine at a first glance.
![image](https://cloud.githubusercontent.com/assets/200952/25456920/a3d79f84-2ad4-11e7-94f8-29fb170f4db2.png)
2. images have a fixed dimension and do not adjust to the dimension of the tool-window
3. vcs-file-watching does not pick up the snapshot.png's automatically but a manual refresh is required  each time to update the r-graphics-tool-window content.

Not sure how easy it will be to overcome these limitations.

**Comment by ktisha** [comment]
@holgerbrandl 
1. ggplot2 doesn't work for me either
2. The same on Ubuntu
3. Works in my case

**Comment by holgerbrandl** [comment]
I've disabled the custom device for 1.0.5. Now the run/debug configurations will fall back to use the default platform device.

I hope you're fine with closing this ticket. I've created a followup with #95.

**Comment by sproshev** [comment]
@holgerbrandl 

2. Adjusting wasn't implemented.
