### ISSUE TITLE
Failed to generate skeleton for 'tcltk'. Exit code: -1

### ISSUE THREAD

**Issue by smalints** [holgerbrandl/r4intellij#89]
Hi, problems in IntelliJ Idea 2017.1

Error Details

Failed to generate skeleton for 'tcltk'. Exit code: -1
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:268)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Thanks.

**Comment by holgerbrandl** [comment]
Works for me. Could you (and also you @PikalaxALT) run the following bits:
```bash
wget https://raw.githubusercontent.com/holgerbrandl/r4intellij/master/r-helpers/skeletonize_package.R

pckgName=tcltk
R -f skeletonize_package.R --args  ${pckgName} ${pckgName}.skeleton.R
```
and attach the resulting `${pckgName}.skeleton.R` (if it is created at all)? 

This will help to narrow down the problem and make R library indexing more robust.

**Comment by PikalaxALT** [comment]
[tcltk.skeleton.R.zip](https://github.com/holgerbrandl/r4intellij/files/965399/tcltk.skeleton.R.zip)

**Comment by holgerbrandl** [comment]
Hmm, the generated skeleton file looks ok to me. The next patch-level release will indicate better what went wrong during index creation.

**Comment by kenahoo** [comment]
I had a similar problem, but in my case with the `'coin'` package.  I ran `skeletonize_package.R` and saw this result:

```
% Rscript ~/Library/Application\ Support/IdeaIC2017.1/R4Intellij/skeletonize_package.R coin /tmp/out
Loading required package: methods
Loading required package: survival
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib/R/3.3/site-library/mvtnorm/libs/mvtnorm.so':
  dlopen(/usr/local/lib/R/3.3/site-library/mvtnorm/libs/mvtnorm.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib
  Referenced from: /usr/local/lib/R/3.3/site-library/mvtnorm/libs/mvtnorm.so
  Reason: image not found
Error: package or namespace load failed for ‘coin’
Execution halted
```

Sure enough, even when I fired up an R interpreter, I couldn't do `library(coin)`.  It turned out to be a problem with its dependency `mvtnorm`, so once I re-installed that and re-installed `coin`, R4IntelliJ was happier.

**Comment by holgerbrandl** [comment]
With v1.0.5 the error boxes will look similar to 
![image](https://cloud.githubusercontent.com/assets/200952/25681157/9bc9e9ee-3053-11e7-83a8-8bbd97fb2498.png)
This should indicate better what goes wrong.

Also the plugin will no longer reattempt to build skeletons for failing packages on each startup.

**Comment by DuM4ll3** [comment]
Hi, had this same issue. installed R by CRAN

```
Failed to generate skeleton for 'tcltk'. The error was:

Erro: package or namespace load failed for ‘tcltk’:
 .onLoad falhou em loadNamespace() para 'tcltk', detalhes:
  chamada: dyn.load(file, DLLpath = DLLpath, ...)
  erro: impossível carregar objeto compartilhado '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/tcltk/libs/tcltk.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/tcltk/libs/tcltk.so, 10): Library not loaded: /opt/X11/lib/libfontconfig.1.dylib
  Referenced from: /usr/local/lib/libtk8.6.dylib
  Reason: Incompatible library version: libtk8.6.dylib requires version 11.0.0 or later, but libfontconfig.1.dylib provides version 10.0.0
```
