### ISSUE TITLE
Fatal exception on startup

### ISSUE THREAD

**Issue by owen0131** [holgerbrandl/r4intellij#94]
I just installed the R 3.4.0 binary for macOS 10.12 (Sierra), and configured the R Interpreter for the very first time in Preferences -> Languages & Frameworks -> R Language. Now whenever I start IntelliJ, I get the following fatal exception:

```
Failed to generate skeleton for 'tcltk'. Exit code: 1
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:268)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I would totally believe that I'm doing something wrong, I just have no idea what. I did initially install R without the **optional** tcltk component, but when I got this error, I reinstalled R with all the components and still get the error.

**Comment by holgerbrandl** [comment]
We had the same issue in #89 but unfortunately it's still not clear what goes wrong. Could your 
```
wget https://raw.githubusercontent.com/holgerbrandl/r4intellij/master/r-helpers/skeletonize_package.R

pckgName=tcltk
R -f skeletonize_package.R --args  ${pckgName} ${pckgName}.skeleton.R
```
in a terminal attach the resulting `${pckgName}.skeleton.R` to this ticket? Thanks!

**Comment by owen0131** [comment]
So that failed with the following error:

```
Error: package or namespace load failed for ‘tcltk’:
 .onLoad failed in loadNamespace() for 'tcltk', details:
  call: fun(libname, pkgname)
  error: X11 library is missing: install XQuartz from xquartz.macosforge.org
Execution halted
```
I purposely never installed XQuartz (and like I mentioned in my first comment, I initially did not install the "optional" tcltk R package at all) because I knew I would not be using any of it's functionality and I didn't want XQuartz installed on my machine.  Seems like although the tcltk package is optional for R, it is _not_ optional for r4intellij. If that is actually the case, I'll just have to bite the bullet and install XQuartz, or run r4intellij without an R interpreter.

**Comment by holgerbrandl** [comment]
XQuartz should not be a dependency. And in fact it is not. Just the indexing of tcltk will fail (and thus you won't get proper completion when using the package).

In the latest version v1.0.5 you will see the error from above in a more descriptive dialog now when the plugin is attempting to the index the `tcltk` for the first time. It won't reattempt to index it again unless you manually trigger an index refresh (Tools->Refresh R Package Index).

I hope this solves your problem. Feel welcome to come back if not.

**Comment by owen0131** [comment]
Works great, thanks!
